OldHouse/Models/Patient.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using OldHouse.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OldHouse.Data
{
    public class Patient
    {
		[Key]
		public int PatientId { get; set; }

		[Required]
        [StringLength(256, ErrorMessage = "Maximum length for first name is {1}")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(256, ErrorMessage = "Maximum length for last name is {1}")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Date Of Birth")]
        public DateTime Birthdate { get; set; }

        [StringLength(256, ErrorMessage = "Maximum length for display name is {1}")]
        public string Gender { get; set; } = "Male";

        [Display(Name = "Blood Type")]
        public string BloodType { get; set; }

        [Display(Name = "Display Name")]
        public string DisplayName
        {
            get { return FirstName + ' ' + LastName; }
            set { }
        }

        public int? MachineId { get; set; }

        [ForeignKey("MachineId")]
        public Machine Machine { get; set; }

        [Display(Name = "Created At")]
		[DataType(DataType.DateTime)]
		public DateTime? CreatedAt { get; set; } = DateTime.Now;

        [Display(Name = "Updated At")]
		[DataType(DataType.DateTime)]
		public DateTime? UpdatedAt { get; set; }

        [NotMapped]
        public IEnumerable<SelectListItem> BloodTypes { get; set; }

        public List<Record> Records { get; set; }
        public Relative Relative { get; set; }
        public List<Alert> Alerts { get; set; }
    }
}

OldHouse/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OldHouse.Data;
using OldHouse.Models;

namespace OldHouse.Controllers
{
    public class PatientsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PatientsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> AssignPatientToMachine(int patientId)
        {
           
                var patient = await _context.Patients.Include(p=>p.Machine).FirstOrDefaultAsync(p => p.PatientId == patientId);
                var machines = _context.Machines.Where(m => (m.Status == Status.AVAILABLE) | (m.MachineId == patient.MachineId));
               
            if(patient.MachineId == null)
            {
                ViewData["MachineId"] = new SelectList(machines, "MachineId", "SerialNumber");
                ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "DisplayName", patient.DisplayName);
                TempData["InfoMessage"] = "Please assign a machine to " + patient.DisplayName;
            }

                if(patient.MachineId != null && patient.Machine.Status == Status.OUT_OF_SERVICE)
                {
                TempData["DangerMessage"] = patient.Machine.SerialNumber + " is out of service.";
                ViewData["MachineId"] = new SelectList(machines, "MachineId", "SerialNumber", patient.Machine.SerialNumber);
                ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "DisplayName", patient.DisplayName);
            }
                if (machines.Count() <=0)
                {
                    TempData["NoMachineAvailable"] = "There are no machines available at this time.";
                    return RedirectToAction(nameof(Details), new { id = patient.PatientId });
                }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AssignPatientToMachine(int patientId, int machineId)
        {
            var patient = await _context.Patients.Include(p=>p.Machine).FirstOrDefaultAsync(p => p.PatientId == patientId);
            var machine = await _context.Machines.FirstOrDefaultAsync(m => m.MachineId == machineId);
            patient.MachineId = machineId;
            machine.Status = Status.IN_USE;
            patient.Machine = machine;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: Patients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Patients.ToListAsync());
        }

        // GET: Patients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patients.Include(p=>p.Machine)
                .FirstOrDefaultAsync(m => m.PatientId == id);

            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }

        // GET: Patients/Create
        public IActionResult Create()
        {
            var patient = new Patient();

            patient.BloodTypes = new List<SelectListItem>
        {
                new SelectListItem {Value="B+",Text="B+"},
                new SelectListItem {Value="O+",Text="O+"},
                new SelectListItem {Value="A+",Text="A+"},
                new SelectListItem {Value="AB+",Text="AB+"},
                new SelectListItem {Value="B-",Text="B-"},
                new SelectListItem {Value="O-",Text="O-"},
                new SelectListItem {Value="A-",Text="A-"},
                new SelectListItem {Value="AB-",Text="AB-"}
        };

            return View(patient);
        }

        // POST: Patients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PatientId,FirstName,LastName,Birthdate,Gender,BloodType,DisplayName,CreatedAt,UpdatedAt")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                _context.Add(patient);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            patient.BloodTypes = new List<SelectListItem>
        {
                new SelectListItem {Value="B+",Text="B+"},
                new SelectListItem {Value="O+",Text="O+"},
                new SelectListItem {Value="A+",Text="A+"},
                new SelectListItem {Value="AB+",Text="AB+"},
                new SelectListItem {Value="B-",Text="B-"},
                new SelectListItem {Value="O-",Text="O-"},
                new SelectListItem {Value="A-",Text="A-"},
                new SelectListItem {Value="AB-",Text="AB-"}
        };

            return View(patient);
        }

        // GET: Patients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patients.FindAsync(id);
            if (patient == null)
            {
                return NotFound();
            }

            patient.BloodTypes = new List<SelectListItem>
        {
                new SelectListItem {Value="B+",Text="B+"},
                new SelectListItem {Value="O+",Text="O+"},
                new SelectListItem {Value="A+",Text="A+"},
                new SelectListItem {Value="AB+",Text="AB+"},
                new SelectListItem {Value="B-",Text="B-"},
                new SelectListItem {Value="O-",Text="O-"},
                new SelectListItem {Value="A-",Text="A-"},
                new SelectListItem {Value="AB-",Text="AB-"}
        };

            return View(patient);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PatientId,FirstName,LastName,Birthdate,Gender,BloodType,DisplayName,CreatedAt,UpdatedAt")] Patient patient)
        {
            if (id != patient.PatientId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patient);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientExists(patient.PatientId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(patient);
        }

        // GET: Patients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patients
                .FirstOrDefaultAsync(m => m.PatientId == id);
            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var patient = await _context.Patients.Include(p=>p.Machine).FirstOrDefaultAsync(p=>p.PatientId == id);
            if(patient.Machine.Status == Status.IN_USE)
            {
                patient.Machine.Status = Status.AVAILABLE;

            }
            _context.Patients.Remove(patient);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PatientExists(int id)
        {
            return _context.Patients.Any(e => e.PatientId == id);
        }
    }
}

OldHouse/Views/Patients/AssignPatientToMachine.cshtml
@model OldHouse.Data.Patient

@{
    ViewData["Title"] = "Assign Patient To Machine";
}

<h2>Assigne Patient To Machine</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        @{
            if (TempData["InfoMessage"] != null)
            {
            <div class="alert alert-info">
                @TempData["InfoMessage"]
            </div>
            }

            if (TempData["DangerMessage"] != null)
            {
            <div class="alert alert-danger">
                @TempData["DangerMessage"]
            </div>
            }
        }

        <form asp-action="AssignPatientToMachine">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MachineId" class="control-label"></label>
                @{
                    if ((ViewBag.MachineId as SelectList).Count() > 0)
                    {
                        <select name="machineId" class="form-control" asp-items="ViewBag.MachineId"><option value="" disabled selected>Select a machine</option></select>
                    }
                    else
                    {
                        <select name="machineId" class="form-control" asp-items="ViewBag.MachineId" disabled><option value="" disabled selected>There are no machine available</option> </select>

                    }
                }
            </div>

            <div class="form-group">
                <label asp-for="PatientId" class="control-label"></label>
                <select name="patientId" class="form-control" asp-for="PatientId" asp-items="ViewBag.PatientId"></select>
            </div>

            <div class="form-group">
                @{
                    if ((ViewBag.MachineId as SelectList).Count() > 0)
                    {
                        <input type="submit" value="Assign" class="btn btn-default" />
                    }
                    else
                    {
                        <input type="submit" disabled value="Assign" class="btn btn-default" />

                    }
                }
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OldHouse/Views/Patients/Create.cshtml
@model OldHouse.Data.Patient

@{
    ViewData["Title"] = "Create";
}

    <h2>Create Patient</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthdate" class="control-label"></label>
                <input asp-for="Birthdate" class="form-control" />
                <span asp-validation-for="Birthdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label><br />
                @Html.RadioButtonFor(model => model.Gender, "Male")
                Male
                @Html.RadioButtonFor(model => model.Gender, "Female")
                Female
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BloodType" class="control-label"></label>
                <select asp-for="BloodType" asp-items="Model.BloodTypes" class="form-control"></select>
                <span asp-validation-for="BloodType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OldHouse/Views/Patients/Delete.cshtml
@model OldHouse.Data.Patient

@{
    ViewData["Title"] = "Delete Patient";
}

    <h2> Delete <span class="text-danger"> @Html.DisplayFor(model => model.DisplayName) </span></h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Birthdate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BloodType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BloodType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PatientId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

OldHouse/Views/Patients/Details.cshtml
@model OldHouse.Data.Patient

@{
    ViewData["Title"] = "Details Patient";
}

<h2>Details</h2>
@{
    if (TempData["NoMachineAvailable"] != null)
    {
    <div class="alert alert-warning">
        @TempData["NoMachineAvailable"]
    </div>
    }
    }
<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BloodType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BloodType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Birthdate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        @{

            if (Model.MachineId != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Machine)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Machine.SerialNumber)
                </dd>

                if (Model.Machine.Status.Equals(Status.OUT_OF_SERVICE))
                {
                    <dt>
                        @Html.DisplayNameFor(model => model.Machine.Status)
                    </dt>
                    <dd>
                        <p><span class="text-danger"> OUT OF SERVICE </span><i> Please press <a asp-controller="Patients" asp-action="AssignPatientToMachine" asp-route-patientId="@Model.PatientId">here</a> to assign another machine</i></p>
                    </dd>
                }
                else if (Model.Machine.Status.Equals(Status.IN_USE))
                {
                    <dt>
                        @Html.DisplayNameFor(model => model.Machine.Status)
                    </dt>
                    <dd>
                        <p><i><span class="text-warning text-uppercase"> In Use</span> </i></p>
                    </dd>
                }

                else if (Model.Machine.Status.Equals(Status.AVAILABLE))
                {
                    <dt>
                        @Html.DisplayNameFor(model => model.Machine.Status)
                    </dt>
                    <dd>
                        <p><i><span class="text-success text-uppercase"> Available</span> </i></p>
                    </dd>
                }

            }
            else
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Machine)
                </dt>
                <dd>
                    <p> <i> Please press <a asp-controller="Patients" asp-action="AssignPatientToMachine" asp-route-patientId="@Model.PatientId">here</a> to assign a machine</i></p>
                </dd>

            }

        }
    </dl>
</div>
<div>

    <a asp-action="Edit" asp-route-id="@Model.PatientId" class="btn btn-warning"><i class="fa fa-edit"></i>  Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

OldHouse/Views/Patients/Edit.cshtml
@model OldHouse.Data.Patient

@{
    ViewData["Title"] = "Edit Patient";
}

<h2>Edit @Model.DisplayName</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PatientId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthdate" class="control-label"></label>
                <input asp-for="Birthdate" class="form-control" />
                <span asp-validation-for="Birthdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label><br />
                @Html.RadioButtonFor(model => model.Gender, "Male")
                Male
                @Html.RadioButtonFor(model => model.Gender, "Female")
                Female
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BloodType" class="control-label"></label>
                <select asp-for="BloodType" asp-items="Model.BloodTypes" class="form-control"></select>
                <span asp-validation-for="BloodType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OldHouse/Views/Patients/Index.cshtml
@model IEnumerable<OldHouse.Data.Patient>

@{
    ViewData["Title"] = "Patients";
}

<h2>Patients</h2>

<p>
    <a class="btn btn-primary" asp-action="Create"> <i class="fas fa-plus"> </i>  Add New Patient</a>
</p>

<div class="input-group">
    <input type="text" class="form-control" id="myInput" onkeyup="myFunction()" title="Type in a patient name" placeholder="Search" style="width:1000px" aria-label="Recipient's username" aria-describedby="basic-addon2">
</div>

<br />
<table class="table" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DisplayName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BloodType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Birthdate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DisplayName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BloodType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Birthdate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PatientId"><i class="fas fa-edit"></i></a> |
                <a asp-action="Details" asp-route-id="@item.PatientId"><i class="fas fa-eye"></i></a> |
                <a asp-action="Delete" asp-route-id="@item.PatientId"><i class="fas fa-trash"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>

<script>
    function myFunction() {
        // Declare variables
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        // Loop through all table rows, and hide those who don't match the search query
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
</script>